[package]
name = "purple"
version = "0.0.1"
license = "GPL-3.0"

[workspace]

[dependencies]
crust = "0.30.0"
hex = "0.3.2"
tokio = "0.1.11"
itc = "0.1.2"
crypto = { path = "src/crypto" } 
jump = { path = "src/jump" }
transactions = { path = "src/transactions" }

[lib]
path = "src/purple/lib.rs"

[[bin]]
path = "src/purple/main.rs"
name = "purple"
