[package]
name = "purple"
version = "0.0.1"
license = "GPL-3.0"

[workspace]

[dependencies]
hex = "0.3.2"
tokio = "0.1.11"
itc = "0.1.2"
log = "0.4.0"
env_logger = "0.6.0"
account = { path = "src/account" }
purple_vm = { path = "src/purple_vm" }
crypto = { path = "src/crypto" } 
jump = { path = "src/jump" }
events = { path = "src/events" }
transactions = { path = "src/transactions" }

[lib]
path = "src/purple/lib.rs"

[[bin]]
path = "src/purple/main.rs"
name = "purple"
