[package]
name = "cuckoo-sys"
version = "0.1.0"
authors = ["Octavian Oncescu <octavonce@gmail.com>"]
edition = "2018"
publish = false

[dependencies]

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }

[features]

default = []
gpu = []