[package]
name = "events"
version = "0.1.0"
authors = []

[dependencies]
causality = { path = "../causality" }
network = { path = "../network" }
crypto = { path = "../crypto" }
transactions = { path = "../transactions" }