[package]
name = "crypto"
version = "0.1.0"
authors = []

[dependencies]
blake2 = "0.8.0"
hex = "0.3.2"
rlp = "0.3.0"
rust_sodium = "0.7.0"
serde = "1.0.59"
serde_derive = "1.0.59"
quickcheck = "0.7.2"
hashdb = { git = "https://github.com/paritytech/parity-common" }
rand = "0.6.0"