[package]
name = "crypto"
version = "0.1.0"
authors = []

[dependencies]
blake2 = "0.7.0"
hex = "0.3.2"
rust_sodium = "0.7.0"
serde = "1.0.59"
serde_derive = "1.0.59"
quickcheck = "0.7.2"
rand = "0.6.0"