[package]
name = "transactions"
version = "0.1.0"
authors = []

[dependencies]
serde = "1.0.59"
serde_derive = "1.0.59"
erased-serde = "0.3.6"
byteorder = "1.2.7"
network = { path = "../network" }
causality = { path = "../causality" }
crypto = { path = "../crypto" }
account = { path = "../account" }