[package]
name = "transactions"
version = "0.1.0"
authors = []

[dependencies]
serde = "1.0.59"
serde_derive = "1.0.59"
byteorder = "1.2.7"
rlp = "0.3.0"
hashdb = "0.3.0"
patricia-trie = "0.3.0"
elastic-array = "0.10.0"
rand = "0.6.0"
network = { path = "../network" }
causality = { path = "../causality" }
crypto = { path = "../crypto" }
account = { path = "../account" }
quickcheck = "0.7.2"