[package]
name = "miner"
version = "0.1.0"
authors = ["Octavian Oncescu <octavonce@gmail.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
cmake = "0.1.24"
fs_extra = "1.1.0"

[features]
default = []
gpu = []