[package]
name = "network"
version = "0.1.0"
authors = []

[dependencies]
serde = "1.0.59"
serde_derive = "1.0.59"
rand = "0.6.0"
byteorder = "1.2.7"
tokio = "0.1.11"
futures = "0.1.25"
env_logger = "0.6.0"
log = "0.4.0"
parking_lot = "0.6"
hex = "0.3.2"
crypto = { path = "../crypto" }
quickcheck = "0.7.2"